module.exports = {
  CONSUMER_KEY        : "YOUR_CONSUMER_KEY",
  CONSUMER_SECRET     : "YOUR_CONSUMER_SECRET",
  ACCESS_TOKEN_KEY    : "YOUR_ACCESS_TOKEN",
  ACCESS_TOKEN_SECRET : "YOUR_TOKEN_SECRET",
  
  USERNAME            : "YOUR_TWITTER_USERNAME"
}