module.exports = [
  {
    keywords: ['thalia', 'thalia agroti'],
    slug: 'thalia-agroti',
    snippet: 'Thalia\'s work mainly revolves around experimental sound creation exploring immersive sonic environments.',
    photo: '/img/thalia.jpeg',
  },
  {
    keywords: ['eleni', 'eleni alexandri'],
    slug: 'eleni-alexandri',
    snippet: 'Eleni is a visual artist focussing on the concept of the archive and archival art.',
    photo: '/img/eleni.jpeg',
  },
  {
    keywords: ['arturas', 'arturas bondarciukas'],
    slug: 'arturas bondarciukas',
    snippet: 'Arturas is working with computer generated imagery, computational arts, and traditional photography.',
    photo: '/img/arturas.jpeg',
  },
  {
    keywords: ['amy', 'amy cartwright'],
    slug: 'amy-cartwright',
    snippet: 'Amy is a dancercreating computational choreographies that use technology within live performance.',
    photo: '/img/amy.jpeg',
  },
  {
    keywords: ['charlotte', 'charlotte dann', '@charlotte_dann'],
    slug: 'charlotte-dann',
    snippet: 'Charlotte\'s work centres around nullifying the contradiction between being a maker and a programmer.',
    photo: '/img/charlotte.jpeg',
  },
  {
    keywords: ['laura', 'laura dekker'],
    slug: 'laura-dekker',
    snippet: 'Laura\'s work explores the reciprocal roles of technologies in how we construct ourselves and our world.',
    photo: '/img/laura.jpeg',
  },
  {
    keywords: ['diane', 'diane edwards'],
    slug: 'diane-edwards',
    snippet: 'Diane focuses on the human microbiome, digital/organic ontologies and questions of more-than-human life.',
    photo: '/img/diane.jpeg',
  },
  {
    keywords: ['saskia', 'saskia freeke', '@sasj nl'],
    slug: 'saskia-freeke',
    snippet: 'Saskia\'s art work focuses on structure, geometry and playfulness by creating novel, tangible interfaces.',
    photo: '/img/saskia.jpeg',
  },
  {
    keywords: ['miduo', 'miduo gao'],
    slug: 'miduo-gao',
    snippet: 'Miduo aims to create artworks that generate public awareness about environmental issues.',
    photo: '/img/miduo.jpeg',
  },
  {
    keywords: ['jakob', 'jakob glock'],
    slug: 'jakob-glock',
    snippet: 'Jakob uses code to build generative systems inspired by nature, science, sound and graphics programming.',
    photo: '/img/jakob.jpeg',
  },
  {
    keywords: ['georgios', 'georgios greekalogerakis'],
    slug: 'georgios-greekalogerakis',
    snippet: 'Georgios examines religion, art, gender, life and death while blending the imaginative and the real.',
    photo: '/img/georgios.jpeg',
  },
  {
    keywords: ['jayson', 'jayson haebich'],
    slug: 'jayson haebich',
    snippet: 'Jayson uses technology to create installations that speculate on present and future forms of technology.',
    photo: '/img/jayson.jpeg',
  },
  {
    keywords: ['jade hall smith', 'jade hall smith hall-smith'],
    slug: 'jade-hall-smith',
    snippet: 'Jade is interested in assistive and rehabilitative technology for people with disabilities.',
    photo: '/img/jade.jpeg',
  },
  {
    keywords: ['freddie', 'freddie hong'],
    slug: 'freddie-hong',
    snippet: 'Freddie explores methods of involving human bodies, and other qualitative matters, in architecture.',
    photo: '/img/freddie.jpeg',
  },
  {
    keywords: ['ewa', 'ewa justka'],
    slug: 'ewa-justka',
    snippet: 'Ewa researches exploration of materiality, ontological systems and modes of quasi-direct perception.',
    photo: '/img/ewa.jpeg',
  },
  {
    keywords: ['natthakit', 'natthakit kangsadansenanon'],
    slug: 'natthakit-kansadansenanon',
    snippet: 'Natthakit is interested in merging intelligent digital technologies into existing objects of daily life.',
    photo: '/img/natthakit.jpeg',
  },
  {
    keywords: ['mehrbano', 'mehrbano khattak'],
    slug: 'mehrbano-khattak',
    snippet: 'Mehrbano is exploring how creative coding and physical computing can enhance her interactive art.',
    photo: '/img/mehrbano.jpeg',
  },
  {
    keywords: ['philip', 'philip liu'],
    slug: 'philip-liu',
    snippet: 'Philip, a multi-disciplinary artist, explores mathematical aesthetics and virtuality through his work.',
    photo: '/img/philip.jpeg',
  },
  {
    keywords: ['alix', 'alix martinez'],
    slug: 'alix-martinez',
    snippet: 'Alix reflects on universal emotions and the relationship between humans with technology.',
    photo: '/img/alix.jpeg',
  },
  {
    keywords: ['friendred', '@ friendred'],
    slug: 'friendred',
    snippet: 'Friendred focuses on a dialogue between spatiotemporal substances, sex and theology.',
    photo: '/img/friendred.jpeg',
  },
  {
    keywords: ['howard', 'howard melnyczuk', '@melnyczuk'],
    slug: 'howard-melnyczuk',
    snippet: 'Howard explores creation, archiving and implementation of data structures to create alternate realities.',
    photo: '/img/howard.jpeg',
  },
  {
    keywords: ['soon', 'soon park'],
    slug: 'soon-park',
    snippet: 'Soon is a graphic designer and performance artist who has worked for today’s largest fashion brands.',
    photo: '/img/soon.jpeg',
  },
  {
    keywords: ['nadia', 'nadia rahat'],
    slug: 'nadia-rahat',
    snippet: 'Nadia creates interactive art works that investigate the relationships between humans and machines.',
    photo: '/img/nadia.jpeg',
  },
  {
    keywords: ['julianne', 'julianne rahimi'],
    slug: 'julianne-rahimi',
    snippet: 'Julianne\'s practice focuses on user interactions and storytelling through various visual forms.',
    photo: '/img/jules.jpeg',
  },
  {
    keywords: ['sabrina', 'sabrina recoules quang'],
    slug: 'sabrina-recoules-quang',
    snippet: 'Sabrina is exploring the similarities between shadow theatre, embodiment and computational practice.',
    photo: '/img/sabrina.jpeg',
  },
  {
    keywords: ['luis', 'luis rubim'],
    slug: 'luis-rubim',
    snippet: 'Luis creates interactive art and physical objects using code to exploring play and mimicry.',
    photo: '/img/luis.jpeg',
  },
  {
    keywords: ['yeoul', 'yeoul son'],
    slug: 'yeoul-son',
    snippet: 'Yeoul focuses on exploring the relationships between data sets and how they can be seen differently.',
    photo: '/img/yeoul.jpeg',
  },
  {
    keywords: ['andrew', 'andrew thompson', '@pdandyuk'],
    slug: 'andrew-thompson',
    snippet: 'Andrew is researching the dichotomy of work and play, and how that manifests itself in instrument design.',
    photo: '/img/andrew.jpeg',
  },
];
