module.exports = [
  {
    keywords: ['thalia', 'thalia agroti'],
    slug: 'thalia-agroti',
    snippet: 'Thalia\'s work mainly revolves around experimental sound creation exploring immersive sonic environments.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/thalia.jpg',
  },
  {
    keywords: ['eleni', 'eleni alexandri'],
    slug: 'eleni-alexandri',
    snippet: 'Eleni is a visual artist focussing on the concept of the archive and archival art.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/eleni.jpg',
  },
  {
    keywords: ['arturas', 'arturas bondarciukas'],
    slug: 'arturas bondarciukas',
    snippet: 'Arturas is working with computer generated imagery, computational arts, and traditional photography.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/arturas.jpg',
  },
  {
    keywords: ['amy', 'amy cartwright'],
    slug: 'amy-cartwright',
    snippet: 'Amy is a dancercreating computational choreographies that use technology within live performance.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/amy.jpg',
  },
  {
    keywords: ['charlotte', 'charlotte dann', '@charlotte_dann'],
    slug: 'charlotte-dann',
    snippet: 'Charlotte\'s work centres around nullifying the contradiction between being a maker and a programmer.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/charlotte.jpg',
  },
  {
    keywords: ['laura', 'laura dekker'],
    slug: 'laura-dekker',
    snippet: 'Laura\'s work explores the reciprocal roles of technologies in how we construct ourselves and our world.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/laura.jpg',
  },
  {
    keywords: ['diane', 'diane edwards'],
    slug: 'diane-edwards',
    snippet: 'Diane focuses on the human microbiome, digital/organic ontologies and questions of more-than-human life.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/diane.jpg',
  },
  {
    keywords: ['saskia', 'saskia freeke', '@sasj_nl'],
    slug: 'saskia-freeke',
    snippet: 'Saskia\'s art work focuses on structure, geometry and playfulness by creating novel, tangible interfaces.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/saskia.jpg',
  },
  {
    keywords: ['miduo', 'miduo gao'],
    slug: 'miduo-gao',
    snippet: 'Miduo aims to create artworks that generate public awareness about environmental issues.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/miduo.jpg',
  },
  {
    keywords: ['jakob', 'jakob glock'],
    slug: 'jakob-glock',
    snippet: 'Jakob uses code to build generative systems inspired by nature, science, sound and graphics programming.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/jakob.jpg',
  },
  {
    keywords: ['georgios', 'georgios greekalogerakis'],
    slug: 'georgios-greekalogerakis',
    snippet: 'Georgios examines religion, art, gender, life and death while blending the imaginative and the real.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/georgios.jpg',
  },
  {
    keywords: ['jayson', 'jayson haebich'],
    slug: 'jayson haebich',
    snippet: 'Jayson uses technology to create installations that speculate on present and future forms of technology.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/jayson.jpg',
  },
  {
    keywords: ['jade hall smith', 'jade hall smith hall-smith'],
    slug: 'jade-hall-smith',
    snippet: 'Jade is interested in assistive and rehabilitative technology for people with disabilities.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/jade.jpg',
  },
  {
    keywords: ['freddie', 'freddie hong'],
    slug: 'freddie-hong',
    snippet: 'Freddie explores methods of involving human bodies, and other qualitative matters, in architecture.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/freddie.jpg',
  },
  {
    keywords: ['ewa', 'ewa justka'],
    slug: 'ewa-justka',
    snippet: 'Ewa researches exploration of materiality, ontological systems and modes of quasi-direct perception.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/ewa.jpg',
  },
  {
    keywords: ['natthakit', 'natthakit kangsadansenanon'],
    slug: 'natthakit-kansadansenanon',
    snippet: 'Natthakit is interested in merging intelligent digital technologies into existing objects of daily life.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/natthakit.jpg',
  },
  {
    keywords: ['mehrbano', 'mehrbano khattak'],
    slug: 'mehrbano-khattak',
    snippet: 'Mehrbano is exploring how creative coding and physical computing can enhance her interactive art.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/mehrbano.jpg',
  },
  {
    keywords: ['philip', 'philip liu'],
    slug: 'philip-liu',
    snippet: 'Philip, a multi-disciplinary artist, explores mathematical aesthetics and virtuality through his work.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/philip.jpg',
  },
  {
    keywords: ['alix', 'alix martinez'],
    slug: 'alix-martinez',
    snippet: 'Alix reflects on universal emotions and the relationship between humans with technology.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/alix.jpg',
  },
  {
    keywords: ['friendred', '@ friendred'],
    slug: 'friendred',
    snippet: 'Friendred focuses on a dialogue between spatiotemporal substances, sex and theology.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/youhong.jpg',
  },
  {
    keywords: ['howard', 'howard melnyczuk', '@melnyczuk'],
    slug: 'howard-melnyczuk',
    snippet: 'Howard explores creation, archiving and implementation of data structures to create alternate realities.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/howard.jpg',
  },
  {
    keywords: ['soon', 'soon park'],
    slug: 'soon-park',
    snippet: 'Soon is a graphic designer and performance artist who has worked for today’s largest fashion brands.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/soon.jpg',
  },
  {
    keywords: ['nadia', 'nadia rahat'],
    slug: 'nadia-rahat',
    snippet: 'Nadia creates interactive art works that investigate the relationships between humans and machines.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/nadia.jpg',
  },
  {
    keywords: ['julianne', 'julianne rahimi'],
    slug: 'julianne-rahimi',
    snippet: 'Julianne\'s practice focuses on user interactions and storytelling through various visual forms.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/jules.jpg',
  },
  {
    keywords: ['sabrina', 'sabrina recoules quang'],
    slug: 'sabrina-recoules-quang',
    snippet: 'Sabrina is exploring the similarities between shadow theatre, embodiment and computational practice.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/sabrina.jpg',
  },
  {
    keywords: ['lius', 'lius rubim'],
    slug: 'lius-rubim',
    snippet: 'Luis creates interactive art and physical objects using code to exploring play and mimicry.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/luis.jpg',
  },
  {
    keywords: ['yeoul', 'yeoul son'],
    slug: 'yeoul-son',
    snippet: 'Yeoul focuses on exploring the relationships between data sets and how they can be seen differently.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/yeoul.jpg',
  },
  {
    keywords: ['andrew', 'andrew thompson', '@pdandyuk'],
    slug: 'andrew-thompson',
    snippet: 'Andrew is researching the dichotomy of work and play, and how that manifests itself in instrument design.',
    photo: 'http://res.cloudinary.com/overlap-show/image/upload/portraits/andrew.jpg',
  },
];
