module.exports = {
  AGROTI          : "Thalia's work mainly revolves around experimental sound creation exploring immersive sonic environments.",
  ALEXANDRI       : "Eleni is a visual artist focussing on the concept of the archive and archival art.",
  BONDARCIUKAS    : "Arturas is working with computer generated imagery, computational arts, and traditional photography.",
  CARTWRIGHT      : "Amy is a dancercreating computational choreographies that use technology within live performance.",
  DANN            : "Charlotte's work centres around nullifying the contradiction between being a maker and a programmer.",
  DEKKER          : "Laura's work explores the reciprocal roles of technologies in how we construct ourselves and our world.",
  EDWARDS         : "Diane focuses on the human microbiome, digital/organic ontologies and questions of more-than-human life.",
  FREEKE          : "Saskia's art work focuses on structure, geometry and playfulness by creating novel, tangible interfaces.",
  GAO             : "Miduo aims to create artworks that generate public awareness about environmental issues.",
  GLOCK           : "Jakob uses code to build generative systems inspired by nature, science, sound and graphics programming.",
  GREEKALOGERAKIS : "Georgios examines religion, art, gender, life and death while blending the imaginative and the real.",
  HAEBICH         : "Jayson uses technology to create installations that speculate on present and future forms of technology.",
  HALL_SMITH      : "Jade is interested in assistive and rehabilitative technology for people with disabilities.",
  HONG            : "Freddie explores methods of involving human bodies, and other qualitative matters, in architecture.",
  JUSTKA          : "Ewa researches exploration of materiality, ontological systems and modes of quasi-direct perception.",
  KANGSADANSENANON: "Natthakit is interested in merging intelligent digital technologies into existing objects of daily life.",
  KHATTAK         : "Mehrbano is exploring how creative coding and physical computing can enhance her interactive art.",
  LIU             : "Philip, a multi-disciplinary artist, explores mathematical aesthetics and virtuality through his work.",
  MARTINEZ        : "Alix reflects on universal emotions and the relationship between humans with technology.",
  FRIENDRED       : "Friendred focuses on a dialogue between spatiotemporal substances, sex and theology.",
  MELNYCZUK       : "Howard explores creation, archiving and implementation of data structures to create alternate realities.",
  PARK            : "Soon is a graphic designer and performance artist who has worked for today’s largest fashion brands.",
  RAHAT           : "Nadia creates interactive art works that investigate the relationships between humans and machines.",
  RAHIMI          : "Julianne's practice focuses on user interactions and storytelling through various visual forms.",
  RECOULES_QUANG  : "Sabrina is exploring the similarities between shadow theatre, embodiment and computational practice.",
  RUBIM           : "Luis creates interactive art and physical objects using code to exploring play and mimicry.",
  SON             : "Yeoul focuses on exploring the relationships between data sets and how they can be seen differently.",
  THOMPSON        : "Andrew is researching the dichotomy of work and play, and how that manifests itself in instrument design.",
  
  UNDEFINED       : "Oops, I didn't quite catch you there! Try again or read about our artists here: http://overlap.show/"
}